apiVersion: v1
kind: Namespace
metadata:
  name: supplysense
  labels:
    app.kubernetes.io/name: supplysense-ai
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: supplysense-config
  namespace: supplysense
data:
  SPRING_PROFILES_ACTIVE: "docker"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  AI_SERVICE_URL: "http://ai-service:8090"
  AUTH_SERVICE_URL: "http://auth-service:8081"
  SUPPLY_CHAIN_SERVICE_URL: "http://supply-chain-service:8082"
  RISK_ENGINE_SERVICE_URL: "http://risk-engine-service:8083"
  EVENT_PROCESSOR_SERVICE_URL: "http://event-processor-service:8084"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8085"
